server:
  port:   8080
#数据源
spring:
  datasource:
    username:   root
    password:   root
    driver-class-name:   com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/springboot-cache?characterEncoding=utf8&useSSL=false
    type: org.apache.commons.dbcp.BasicDataSource


